name: Serv00保活进程

on:
  schedule:
    - cron: '3 22 * * *' #北京时间6点
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get install sshpass
          sudo apt-get install jq

      - name: 登录serv00并执行保活脚本
        env:
          HOSTS_JSON: ${{ secrets.HOSTS_JSON }}
        run: |
          cd Serv00/ && chmod +x ./revive.sh
          ./revive.sh
